AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 130

Naming/AsciiIdentifiers:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

Metrics/ParameterLists:
  Max: 10

Style/AsciiComments:
  Enabled: false