dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.6.3
before_install:
  - gem install bundler -v 2.0.2
  - export GR_VERSION=0.41.2
  - chmod +x ./test/ci/install_gr.sh
  - ./test/ci/install_gr.sh
  - export GRDIR=$HOME/GR/$GR_VERSION/gr
cache:
  directories:
    - $HOME/GR
script: bundle exec rake test
