dist: bionic
services:
  - xvfb
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
before_install:
  - export GR_VERSION=0.47.2
  - chmod +x ./test/ci/install_gr.sh
  - ./test/ci/install_gr.sh
  - export GRDIR=$HOME/GR/$GR_VERSION/gr
cache:
  bundler: true
  directories:
    - $HOME/GR
script: bundle exec rake test
