name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - head
        exclude:
          - { os: windows , ruby: head }

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      
      - name: Set up GR
        if: >-
          matrix.os != 'ubuntu'
        run: |
          export GR_VERSION=0.53.0
          chmod +x ./test/ci/install_gr.sh
          ./test/ci/install_gr.sh
          export GRDIR=$HOME/GR/$GR_VERSION/gr

      - run: gem install bundler

      - run: bundle update

      - run: bundle exec rake test
