name: Windows

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          mingw: _upgrade_ libffi

      - name: Install Bundler
        run: |
          gem install bundler

      - name: Install latest Fiddle
        run: |
          gem install specific_install
          gem specific_install https://github.com/ruby/fiddle

      - name: Install dependencies
        run: |
          bundle install

      - name: Test
        run: |
          bundle exec rake test
